version: '3.7'
services:
  web:
    image: nginx
    volumes:
    - ./templates:/etc/nginx/templates
    - ./site:/usr/share/nginx/html:ro
    - ./nginx.conf:/etc/nginx/nginx.conf:ro 
    ports:
    - "8080:80"
    environment:
    - NGINX_HOST=localhost
    - NGINX_PORT=80